// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsbBIxK1Nx3yGN4anyKfXCUWEf9bOSY9I',
    appId: '1:268295066252:web:e01734bbe7c21c5adde1a9',
    messagingSenderId: '268295066252',
    projectId: 'shoppingapp-e3f50',
    authDomain: 'shoppingapp-e3f50.firebaseapp.com',
    storageBucket: 'shoppingapp-e3f50.appspot.com',
    measurementId: 'G-3V63727S2Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKT8r7ORrKDiVoCMFlFsKnuAaX8wJxEEk',
    appId: '1:268295066252:android:7a91c98e7e43925edde1a9',
    messagingSenderId: '268295066252',
    projectId: 'shoppingapp-e3f50',
    storageBucket: 'shoppingapp-e3f50.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwnlg6X_Uo8zkX1kTGpYIjSlU-HeIYTlc',
    appId: '1:268295066252:ios:60c5534e8f76c793dde1a9',
    messagingSenderId: '268295066252',
    projectId: 'shoppingapp-e3f50',
    storageBucket: 'shoppingapp-e3f50.appspot.com',
    iosBundleId: 'com.example.bagShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsbBIxK1Nx3yGN4anyKfXCUWEf9bOSY9I',
    appId: '1:268295066252:web:c9fc08edb382f095dde1a9',
    messagingSenderId: '268295066252',
    projectId: 'shoppingapp-e3f50',
    authDomain: 'shoppingapp-e3f50.firebaseapp.com',
    storageBucket: 'shoppingapp-e3f50.appspot.com',
    measurementId: 'G-G1SFQXKNJK',
  );
}
