// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDlWcFhRlymHOJfqcjEGZiDk02fd3dZNU',
    appId: '1:744143365152:android:73b32a91dd1b9b15078845',
    messagingSenderId: '744143365152',
    projectId: 'pizzaapp-c7a34',
    databaseURL: 'https://pizzaapp-c7a34-default-rtdb.firebaseio.com',
    storageBucket: 'pizzaapp-c7a34.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAX0bsy6qlYKuR6Nkffld9nf53x_S4Pa9c',
    appId: '1:744143365152:ios:505de20d40edbdb7078845',
    messagingSenderId: '744143365152',
    projectId: 'pizzaapp-c7a34',
    databaseURL: 'https://pizzaapp-c7a34-default-rtdb.firebaseio.com',
    storageBucket: 'pizzaapp-c7a34.appspot.com',
    iosBundleId: 'com.example.bagShop',
  );

}